# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-15 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0006_phonedevice_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedevice',
            name='extension',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{0,5}$', 'Extension must be blank or up to 5 numeric values')], verbose_name='extension'),
        ),
    ]
